# This file was generated by GoReleaser. DO NOT EDIT.
class TrellisCli < Formula
  desc "A CLI to manage Trellis projects"
  homepage "https://roots.io/trellis"
  url "https://github.com/roots/trellis-cli/releases/download/v0.3.1/trellis_0.3.1_Darwin_x86_64.tar.gz"
  version "0.3.1"
  sha256 "982bf1eec69c4a186ce93baa4c7d2a55e607dd7bbf0f3af61c145803846cee8c"

  def install
    bin.install "trellis"
  end

  test do
    system "#{bin}/trellis --autocomplete-install"
    system "#{bin}/trellis -v"
  end
end
