# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TrellisCli < Formula
  desc "A CLI to manage Trellis projects"
  homepage "https://roots.io/trellis"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roots/trellis-cli/releases/download/v1.1.0/trellis_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "a10d0e2c60af1b9842c79b1d5da32305c4a133838667a63d69041a647ea2372c"

      def install
        bin.install "trellis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/roots/trellis-cli/releases/download/v1.1.0/trellis_1.1.0_Darwin_arm64.tar.gz"
      sha256 "94a8bcf5c999374f98a0cb5e9e90fb27c28e0cccf35b0d6310b95a17db70d3b4"

      def install
        bin.install "trellis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/roots/trellis-cli/releases/download/v1.1.0/trellis_1.1.0_Linux_x86_64.tar.gz"
      sha256 "b5b167530affb86b234c77c25e520e47633f3b465a10c95363a8263b86857e6a"

      def install
        bin.install "trellis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/roots/trellis-cli/releases/download/v1.1.0/trellis_1.1.0_Linux_arm64.tar.gz"
      sha256 "cbee200d335fcad4ec8e35a48fcb915a2261b05ad8c186c886976e8d0d2a377d"

      def install
        bin.install "trellis"
      end
    end
  end

  test do
    system "#{bin}/trellis --autocomplete-install"
    system "#{bin}/trellis -v"
  end
end
