# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TrellisCli < Formula
  desc "A CLI to manage Trellis projects"
  homepage "https://roots.io/trellis"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/roots/trellis-cli/releases/download/v1.0.0/trellis_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "e8ce7454201f5b5305ec7e58a2dcd2fe447d1c07808e70fb88fa57f5fc9701b0"

      def install
        bin.install "trellis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/roots/trellis-cli/releases/download/v1.0.0/trellis_1.0.0_Linux_x86_64.tar.gz"
      sha256 "de375e4c54c67dbe1bc2c63de25ba4880436eb8d449e2997b2114f5a51ae1ce4"

      def install
        bin.install "trellis"
      end
    end
  end

  test do
    system "#{bin}/trellis --autocomplete-install"
    system "#{bin}/trellis -v"
  end
end
